name: Email on push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.SMTP_USERNAME}}
        password: ${{secrets.SMTP_PASSWORD}}
        subject: a7a
        body: a7a7a
        to: ahmadsamehh99@gmail.com
        from: ahmadsameh99@gmail.com
